Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-05, with the labels that each got.

#91 Add BOOST_TEST_DYN_LINK to all unit tests targets
  extensions/entsoe/CMakeLists.txt
  extensions/iidm/CMakeLists.txt
  test/iidm/CMakeLists.txt
  test/logging/CMakeLists.txt
  test/math/CMakeLists.txt
  test/network/CMakeLists.txt
  test/stdcxx/CMakeLists.txt
  test/xml/CMakeLists.txt
Labels: PR: ready-to-be-merged, bug

#92 Install windows DLLs in <INSTALL_PATH>/bin
  extensions/entsoe/CMakeLists.txt
  extensions/iidm/CMakeLists.txt
  src/CMakeLists.txt
  src/test/CMakeLists.txt
Labels: PR: ready-to-be-merged

#89 Allow to write IIDM-XML files in previous versions
  include/powsybl/iidm/converter/Constants.hpp
  include/powsybl/iidm/converter/xml/CurrentLimitsXml.hpp
  include/powsybl/iidm/converter/xml/IidmXmlVersion.hpp
  src/iidm/converter/xml/AbstractConnectableXml.hpp
  src/iidm/converter/xml/AbstractConnectableXml.hxx
  src/iidm/converter/xml/AbstractIdentifiableXml.hxx
  src/iidm/converter/xml/AbstractTransformerXml.hxx
  src/iidm/converter/xml/CurrentLimitsXml.cpp
  src/iidm/converter/xml/DanglingLineXml.cpp
  src/iidm/converter/xml/IidmXmlVersion.cpp
  src/iidm/converter/xml/LineXml.cpp
  src/iidm/converter/xml/NetworkXml.cpp
  src/iidm/converter/xml/NodeBreakerViewInternalConnectionXml.cpp
  src/iidm/converter/xml/PropertiesXml.cpp
  src/iidm/converter/xml/ReactiveLimitsXml.cpp
  src/iidm/converter/xml/TerminalRefXml.cpp
  src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
  src/iidm/converter/xml/TieLineXml.cpp
  src/iidm/converter/xml/TwoWindingsTransformerXml.cpp
  src/iidm/converter/xml/VoltageLevelXml.cpp
Labels: PR: waiting-for-review

#96 Fix boost install commands for windows
  README.md
Labels: PR: waiting-for-review

#102 New extension design
  include/powsybl/iidm/Extendable.hpp
  include/powsybl/iidm/Extendable.hxx
  include/powsybl/iidm/ExtensionAdder.hpp
  src/CMakeLists.txt
  src/iidm/ExtensionAdder.cpp
  test/iidm/CMakeLists.txt
  test/iidm/ExtensionAdderTest.cpp
Labels: PR: ready-to-be-merged
