Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-07, with the labels that each got.

#139 Update version to v1.1.2
  CMakeLists.txt
Labels: PR: next-release

#93 [IIDM v1.2] Add regulation for shunt compensators
  extensions/iidm/resources/coordinatedReactiveControl.xml
  extensions/iidm/resources/twoWindingsTransformerPhaseAngleClock.xml
  include/powsybl/iidm/ShuntCompensator.hpp
  include/powsybl/iidm/ShuntCompensatorAdder.hpp
  include/powsybl/iidm/TapChanger.hpp
  include/powsybl/iidm/TapChanger.hxx
  include/powsybl/iidm/ValidationUtils.hpp
  src/iidm/PhaseTapChanger.cpp
  src/iidm/PhaseTapChangerAdder.cpp
  src/iidm/RatioTapChanger.cpp
  src/iidm/RatioTapChangerAdder.cpp
  src/iidm/ShuntCompensator.cpp
  src/iidm/ShuntCompensatorAdder.cpp
  src/iidm/ValidationUtils.cpp
  src/iidm/converter/xml/AbstractTransformerXml.hpp
  src/iidm/converter/xml/AbstractTransformerXml.hxx
  src/network/EurostagFactory.cpp
  test/iidm/PhaseTapChangerTest.cpp
  test/iidm/RatioTapChangerTest.cpp
  test/iidm/ShuntCompensatorTest.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
  test/iidm/TwoWindingsTransformerTest.cpp
  test/resources/V1_2/completeThreeWindingsTransformerRoundTripRef.xml
  test/resources/V1_2/danglingLine.xml
  test/resources/V1_2/eurostag-tutorial-example1-properties.xml
  test/resources/V1_2/eurostag-tutorial-example1-with-terminalMock-ext.xml
  test/resources/V1_2/eurostag-tutorial-example1.xml
  test/resources/V1_2/eurostag-tutorial1-lf.xml
  test/resources/V1_2/threeWindingsTransformerRoundTripRef.xml
  test/resources/V1_2/tieline.xml
Labels: PR: waiting-for-review

#136 [IIDM v1.2] Fix serialization with no exported extensions
  include/powsybl/iidm/converter/ExportOptions.hpp
  src/iidm/converter/ExportOptions.cpp
  src/iidm/converter/xml/NetworkXml.cpp
  test/iidm/converter/ExportOptionsTest.cpp
  test/iidm/converter/ImportOptionsTest.cpp
  test/iidm/converter/xml/CMakeLists.txt
  test/iidm/converter/xml/SkipExtensionTest.cpp
  test/resources/V1_0/noExtension.xml
Labels: PR: ready-to-be-merged, bug

#145 Fix crash when removing a VoltageLevel
  include/powsybl/iidm/NetworkIndex.hpp
  include/powsybl/iidm/NetworkIndex.hxx
  src/iidm/NetworkIndex.cpp
  src/iidm/VoltageLevelAdder.cpp
  test/iidm/BusBreakerVoltageLevelTest.cpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
Labels: PR: ready-to-be-merged, bug

#144 Fix ext-path parsing in iidm-benchmark tool
  tools/benchmark/Benchmark.cpp
Labels: PR: ready-to-be-merged, bug

#149 [IIDM v1.2] Add checks for HVDC lines (power factor and loss factor) (#127 and #128)
  include/powsybl/iidm/ValidationUtils.hpp
  src/iidm/HvdcLine.cpp
  src/iidm/HvdcLineAdder.cpp
  src/iidm/ValidationUtils.cpp
  test/iidm/HvdcLineTest.cpp
  test/iidm/LccConverterStationTest.cpp
  test/iidm/NetworkFactory.cpp
  test/iidm/VscConverterStationTest.cpp
  test/resources/V1_0/LccRoundTripRef.xml
  test/resources/V1_0/VscRoundTripRef.xml
  test/resources/V1_1/LccRoundTripRef.xml
  test/resources/V1_1/VscRoundTripRef.xml
  test/resources/V1_2/LccRoundTripRef.xml
  test/resources/V1_2/VscRoundTripRef.xml
Labels: PR: ready-to-be-merged

#150 [IIDM v1.2] Use new extension API for CoordinatedReactiveControl (#120)
  extensions/iidm/CMakeLists.txt
  extensions/iidm/include/powsybl/iidm/extensions/iidm/CoordinatedReactiveControlAdder.hpp
  extensions/iidm/src/CoordinatedReactiveControlAdder.cpp
  extensions/iidm/src/CoordinatedReactiveControlXmlSerializer.cpp
  extensions/iidm/test/CoordinatedReactiveControlTest.cpp
Labels: PR: ready-to-be-merged

#141 [IIDM V1.2] Add a convenient function to get a Terminal from its node (#67+#75)
  include/powsybl/iidm/VoltageLevelViews.hpp
  include/powsybl/math/UndirectedGraph.hpp
  include/powsybl/math/UndirectedGraph.hxx
  src/iidm/NodeBreakerVoltageLevelViews.cpp
  src/iidm/NodeBreakerVoltageLevelViews.hpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
  test/math/UndirectedGraphTest.cpp
Labels: PR: ready-to-be-merged

#151 [IIDM v1.2] Use new extension API for TwoWindingsTransformerPhaseAngleClock (#120)
  extensions/iidm/CMakeLists.txt
  extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockAdder.hpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClock.cpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockAdder.cpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/test/TwoWindingsTransformerPhaseAngleClockTest.cpp
Labels: PR: ready-to-be-merged

#152 [IIDM v1.2] Use new extension api for ThreeWindingsTransformerPhaseAngleClock extension (#120)
  extensions/iidm/CMakeLists.txt
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockAdder.hpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClock.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockAdder.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/test/ThreeWindingsTransformerPhaseAngleClockTest.cpp
Labels: PR: ready-to-be-merged

#153 [IIDM v1.2] Use new extension api for EntsoeArea (#120)
  extensions/entsoe/CMakeLists.txt
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/EntsoeAreaAdder.hpp
  extensions/entsoe/src/EntsoeAreaAdder.cpp
  extensions/entsoe/src/EntsoeAreaXmlSerializer.cpp
  extensions/entsoe/test/EntsoeAreaTest.cpp
Labels: PR: ready-to-be-merged

#154 [IIDM v1.2] Use new extension api for MergedXnode (#120)
  extensions/entsoe/CMakeLists.txt
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnodeAdder.hpp
  extensions/entsoe/src/MergedXnode.cpp
  extensions/entsoe/src/MergedXnodeAdder.cpp
  extensions/entsoe/src/MergedXnodeXmlSerializer.cpp
  extensions/entsoe/test/MergedXnodeTest.cpp
Labels: PR: ready-to-be-merged
