Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-11, with the labels that each got.

#207 3wt leg getterminal
  include/powsybl/iidm/ThreeWindingsTransformer.hpp
  src/iidm/ThreeWindingsTransformer.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
Labels: Breaking change, PR: waiting-for-review

#211 Fix multi-variant implementation by adding the Network in the index
  include/powsybl/iidm/NetworkIndex.hpp
  include/powsybl/iidm/NetworkIndex.hxx
  include/powsybl/stdcxx/instanceof.hpp
  src/iidm/Network.cpp
  src/iidm/NetworkIndex.cpp
  test/iidm/CMakeLists.txt
  test/iidm/NetworkExtension.cpp
  test/iidm/NetworkExtension.hpp
  test/iidm/NetworkIndexTest.cpp
  test/iidm/NetworkTest.cpp
Labels: PR: waiting-for-review, bug

#200 [IIDM v1.3] Add SlackTerminal extension
  include/powsybl/iidm/AbstractMultiVariantIdentifiableExtension.hpp
  include/powsybl/iidm/extensions/SlackTerminal.hpp
  include/powsybl/iidm/extensions/SlackTerminalAdder.hpp
  include/powsybl/iidm/util/TerminalFinder.hpp
  include/powsybl/network/FictitiousSwitchFactory.hpp
  include/powsybl/stdcxx/instanceof.hpp
  src/CMakeLists.txt
  src/iidm/extensions/LoadDetail.cpp
  src/iidm/extensions/SlackTerminal.cpp
  src/iidm/extensions/SlackTerminalAdder.cpp
  src/iidm/util/TerminalFinder.cpp
  src/network/FictitiousSwitchFactory.cpp
  test/iidm/CMakeLists.txt
  test/iidm/extensions/SlackTerminalTest.cpp
  test/iidm/util/TerminalFinderTest.cpp
Labels: PR: ready-to-be-merged

#212 Refactor VariantArray
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/NetworkVariant.hpp
  include/powsybl/iidm/Variant.hpp
  include/powsybl/iidm/VariantArray.hpp
  include/powsybl/iidm/VariantArray.hxx
  include/powsybl/iidm/VariantManagerSupplier.hpp
  src/CMakeLists.txt
  src/iidm/BusBreakerVoltageLevel.cpp
  src/iidm/BusBreakerVoltageLevel.hpp
  src/iidm/BusBreakerVoltageLevelVariant.hpp
  src/iidm/Network.cpp
  src/iidm/NetworkVariant.cpp
  src/iidm/NodeBreakerVoltageLevel.cpp
  src/iidm/NodeBreakerVoltageLevel.hpp
  src/iidm/NodeBreakerVoltageLevelVariant.hpp
  src/iidm/VariantArray.hxx
Labels: PR: ready-to-be-merged

#214 [IIDM v1.3] Add BusbarSectionPosition (#191)
  extensions/CMakeLists.txt
  extensions/sld/CMakeLists.txt
  extensions/sld/include/powsybl/iidm/extensions/sld/BusbarSectionPosition.hpp
  extensions/sld/include/powsybl/iidm/extensions/sld/BusbarSectionPositionAdder.hpp
  extensions/sld/include/powsybl/iidm/extensions/sld/BusbarSectionPositionXmlSerializer.hpp
  extensions/sld/resources/busbarSectionPosition.xml
  extensions/sld/src/BusbarSectionPosition.cpp
  extensions/sld/src/BusbarSectionPositionAdder.cpp
  extensions/sld/src/BusbarSectionPositionXmlSerializer.cpp
  extensions/sld/src/Sld.cpp
  extensions/sld/test/BusbarSectionPositionTest.cpp
  extensions/sld/test/sld.cpp
  sonar-project.properties
Labels: PR: waiting-for-review

#218 Refactor variants
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/NetworkVariant.hpp
  include/powsybl/iidm/Variant.hpp
  include/powsybl/iidm/Variant.hxx
  include/powsybl/iidm/VariantArray.hpp
  include/powsybl/iidm/VariantArray.hxx
  src/iidm/BusBreakerVoltageLevel.cpp
  src/iidm/BusBreakerVoltageLevel.hpp
  src/iidm/BusBreakerVoltageLevelVariant.cpp
  src/iidm/BusBreakerVoltageLevelVariant.hpp
  src/iidm/Network.cpp
  src/iidm/NetworkVariant.cpp
  src/iidm/NodeBreakerVoltageLevel.cpp
  src/iidm/NodeBreakerVoltageLevel.hpp
  src/iidm/NodeBreakerVoltageLevelVariant.cpp
  src/iidm/NodeBreakerVoltageLevelVariant.hpp
Labels: PR: ready-to-be-merged

#217 Add connected/synchronous components
  include/powsybl/iidm/AbstractComponentsManager.hpp
  include/powsybl/iidm/Bus.hpp
  include/powsybl/iidm/Component.hpp
  include/powsybl/iidm/ComponentConstants.hpp
  include/powsybl/iidm/ConnectedComponentsManager.hpp
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/NetworkVariant.hpp
  include/powsybl/iidm/NetworkViews.hpp
  include/powsybl/iidm/SynchronousComponentsManager.hpp
  include/powsybl/iidm/util/ConnectedComponents.hpp
  include/powsybl/math/ConnectedComponentsComputationResult.hpp
  include/powsybl/math/GraphUtil.hpp
  include/powsybl/math/UndirectedGraph.hxx
  src/CMakeLists.txt
  src/iidm/AbstractComponentsManager.cpp
  src/iidm/Bus.cpp
  src/iidm/BusBreakerVoltageLevel.cpp
  src/iidm/CalculatedBus.cpp
  src/iidm/CalculatedBus.hpp
  src/iidm/Component.cpp
  src/iidm/ConfiguredBus.cpp
  src/iidm/ConfiguredBus.hpp
  src/iidm/ConnectedComponent.cpp
  src/iidm/ConnectedComponent.hpp
  src/iidm/ConnectedComponentsManager.cpp
  src/iidm/HvdcConverterStation.cpp
  src/iidm/MergedBus.cpp
  src/iidm/MergedBus.hpp
  src/iidm/Network.cpp
  src/iidm/NetworkVariant.cpp
  src/iidm/NetworkViews.cpp
  src/iidm/NodeTerminal.cpp
  src/iidm/NodeTerminal.hpp
  src/iidm/SynchronousComponent.cpp
  src/iidm/SynchronousComponent.hpp
  src/iidm/SynchronousComponentsManager.cpp
  src/iidm/util/ConnectedComponents.cpp
  src/math/ConnectedComponentsComputationResult.cpp
  src/math/GraphUtil.cpp
  test/iidm/CMakeLists.txt
  test/iidm/ComponentsTest.cpp
Labels: PR: corrected, PR: ready-to-be-merged

#213 [IIDM v1.3] Add Enum to change behaviour in case of IIDM version incompatibility
  include/powsybl/iidm/converter/ExportOptions.hpp
  include/powsybl/iidm/converter/xml/IidmXmlUtil.hpp
  src/iidm/converter/ExportOptions.cpp
  src/iidm/converter/xml/IidmXmlUtil.cpp
  src/iidm/converter/xml/StaticVarCompensatorXml.cpp
  src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
  src/iidm/converter/xml/VoltageLevelXml.cpp
  test/iidm/converter/ExportOptionsTest.cpp
  test/iidm/converter/xml/CMakeLists.txt
  test/iidm/converter/xml/IidmXmlUtilTest.cpp
Labels: PR: waiting-for-review

#215 [IIDM v1.3] Add ConnectablePosition extension (#191)
  extensions/sld/CMakeLists.txt
  extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePosition.hpp
  extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePositionAdder.hpp
  extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePositionXmlSerializer.hpp
  extensions/sld/resources/connectablePositionFeeder0.xml
  extensions/sld/resources/connectablePositionFeeders123.xml
  extensions/sld/src/ConnectablePosition.cpp
  extensions/sld/src/ConnectablePositionAdder.cpp
  extensions/sld/src/ConnectablePositionXmlSerializer.cpp
  extensions/sld/src/Sld.cpp
  extensions/sld/test/ConnectablePositionTest.cpp
Labels: PR: ready-to-be-merged

#225 Fix performance issue with boost::range::join
  include/powsybl/stdcxx/flattened.hpp
  src/iidm/BusBreakerVoltageLevel.cpp
  src/iidm/MergedBus.cpp
  src/iidm/NetworkViews.cpp
  src/iidm/Substation.cpp
Labels: PR: waiting-for-review, bug
