Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-04, with the labels that each got.

#77 Refactor to do not hide setLossFactor
  include/powsybl/iidm/HvdcConverterStation.hpp
  include/powsybl/iidm/LccConverterStation.hpp
  include/powsybl/iidm/VscConverterStation.hpp
  src/iidm/HvdcConverterStation.cpp
  src/iidm/LccConverterStation.cpp
  src/iidm/VscConverterStation.cpp
Labels: PR: ready-to-be-merged, PR: waiting-for-review

#78 Fix BusbarSection implementation to be compliant with Java implementation
  include/powsybl/iidm/BusbarSection.hpp
  src/iidm/BusbarSection.cpp
  src/iidm/BusbarSectionAdder.cpp
Labels: PR: ready-to-be-merged

#42 Windows porting
  .github/workflows/ci-sonar.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  extensions/entsoe/CMakeLists.txt
  extensions/iidm/CMakeLists.txt
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClock.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/test/ThreeWindingsTransformerPhaseAngleClockTest.cpp
  include/powsybl/iidm/ExtensionProviders.hpp
  include/powsybl/iidm/NetworkIndex.hpp
  include/powsybl/iidm/PhaseTapChanger.hpp
  include/powsybl/iidm/Properties.hpp
  include/powsybl/iidm/TwoWindingsTransformer.hpp
  include/powsybl/iidm/VariantManager.hpp
  include/powsybl/iidm/VoltageLevel.hxx
  include/powsybl/math/UndirectedGraph.hxx
  include/powsybl/stdcxx/demangle.hpp
  include/powsybl/stdcxx/typeinfo.hpp
  include/powsybl/test/ExtensionFixture.hpp
  include/powsybl/xml/XmlString.hpp
  src/CMakeLists.txt
  src/iidm/ExtensionProviders.cpp
  src/iidm/converter/xml/TerminalRefXml.cpp
  src/stdcxx/demangle.cpp
  src/stdcxx/time.cpp
  src/test/CMakeLists.txt
  test/iidm/CMakeLists.txt
  test/iidm/NodeBreakerVoltageLevelTest.cpp
  test/logging/CMakeLists.txt
  test/logging/LoggerFactoryTest.cpp
  test/math/CMakeLists.txt
  test/network/CMakeLists.txt
  test/resources/danglingLine.xml
  test/resources/tieline.xml
  test/stdcxx/CMakeLists.txt
  test/xml/CMakeLists.txt
  tools/benchmark/CMakeLists.txt
Labels: PR: ready-to-be-merged

#79 Clang tidy
  .clang-tidy
  .github/workflows/ci.yml
  cmake/Doxygen.cmake
  extensions/entsoe/test/.clang-tidy
  extensions/entsoe/test/MergedXnodeTest.cpp
  extensions/iidm/test/.clang-tidy
  include/powsybl/iidm/InjectionAdder.hxx
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/PhaseTapChangerHolder.hpp
  include/powsybl/iidm/Properties.hpp
  include/powsybl/iidm/Terminal.hpp
  include/powsybl/iidm/ThreeWindingsTransformerAdder.hpp
  include/powsybl/iidm/VariantManagerHolder.hpp
  include/powsybl/xml/XmlCharConversion.hpp
  src/iidm/ThreeWindingsTransformerAdder.cpp
  src/stdcxx/time.cpp
  src/test/.clang-tidy
  src/xml/XmlCharConversion.cpp
  src/xml/XmlStreamReader.cpp
  src/xml/XmlStreamWriter.cpp
  test/.clang-tidy
  test/iidm/BatteryTest.cpp
  test/iidm/BusBreakerVoltageLevelTest.cpp
  test/iidm/DanglingLineTest.cpp
  test/iidm/GeneratorTest.cpp
  test/iidm/HvdcLineTest.cpp
  test/iidm/LineTest.cpp
  test/iidm/LoadTest.cpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
  test/iidm/ShuntCompensatorTest.cpp
  test/iidm/StaticVarCompensatorTest.cpp
  test/iidm/SubstationTest.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
  test/iidm/TieLineTest.cpp
  test/iidm/TwoWindingsTransformerTest.cpp
  test/iidm/VscConverterStationTest.cpp
  test/math/UndirectedGraphTest.cpp
Labels: PR: ready-to-be-merged

#80 Network identifiable
  include/powsybl/iidm/Bus.hpp
  include/powsybl/iidm/Connectable.hpp
  include/powsybl/iidm/HvdcLine.hpp
  include/powsybl/iidm/Identifiable.hpp
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/Substation.hpp
  include/powsybl/iidm/Switch.hpp
  include/powsybl/iidm/VoltageLevel.hpp
  src/iidm/Bus.cpp
  src/iidm/CalculatedBus.cpp
  src/iidm/CalculatedBus.hpp
  src/iidm/ConfiguredBus.cpp
  src/iidm/ConfiguredBus.hpp
  src/iidm/MergedBus.cpp
  src/iidm/MergedBus.hpp
  src/iidm/Network.cpp
  src/iidm/Switch.cpp
  test/iidm/BusBreakerVoltageLevelTest.cpp
  test/iidm/NetworkTest.cpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
Labels: PR: waiting-for-review

#81 Check unique
  include/powsybl/iidm/BusAdder.hpp
  include/powsybl/iidm/BusbarSectionAdder.hpp
  include/powsybl/iidm/HvdcLineAdder.hpp
  include/powsybl/iidm/IdentifiableAdder.hpp
  include/powsybl/iidm/IdentifiableAdder.hxx
  include/powsybl/iidm/InjectionAdder.hpp
  include/powsybl/iidm/InjectionAdder.hxx
  include/powsybl/iidm/InternalConnectionAdder.hpp
  include/powsybl/iidm/LineAdder.hpp
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/SubstationAdder.hpp
  include/powsybl/iidm/SwitchAdder.hpp
  include/powsybl/iidm/SwitchAdder.hxx
  include/powsybl/iidm/ThreeWindingsTransformerAdder.hpp
  include/powsybl/iidm/TieLineAdder.hpp
  include/powsybl/iidm/TwoWindingsTransformerAdder.hpp
  include/powsybl/iidm/VoltageLevelAdder.hpp
  include/powsybl/iidm/util/Identifiables.hpp
  include/powsybl/stdcxx/Predicate.hpp
  src/CMakeLists.txt
  src/iidm/BatteryAdder.cpp
  src/iidm/BusAdder.cpp
  src/iidm/BusbarSectionAdder.cpp
  src/iidm/DanglingLineAdder.cpp
  src/iidm/GeneratorAdder.cpp
  src/iidm/HvdcLineAdder.cpp
  src/iidm/InternalConnectionAdder.cpp
  src/iidm/LccConverterStationAdder.cpp
  src/iidm/LineAdder.cpp
  src/iidm/LoadAdder.cpp
  src/iidm/ShuntCompensatorAdder.cpp
  src/iidm/StaticVarCompensatorAdder.cpp
  src/iidm/SubstationAdder.cpp
  src/iidm/SwitchAdder.cpp
  src/iidm/ThreeWindingsTransformerAdder.cpp
  src/iidm/TieLineAdder.cpp
  src/iidm/TwoWindingsTransformerAdder.cpp
  src/iidm/VoltageLevelAdder.cpp
  src/iidm/VscConverterStationAdder.cpp
  src/iidm/util/Identifiables.cpp
  test/iidm/BatteryTest.cpp
  test/iidm/DanglingLineTest.cpp
  test/iidm/GeneratorTest.cpp
  test/iidm/HvdcLineTest.cpp
  test/iidm/LccConverterStationTest.cpp
  test/iidm/LineTest.cpp
  test/iidm/LoadTest.cpp
  test/iidm/NetworkTest.cpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
  test/iidm/ShuntCompensatorTest.cpp
  test/iidm/StaticVarCompensatorTest.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
  test/iidm/TieLineTest.cpp
  test/iidm/TwoWindingsTransformerTest.cpp
  test/iidm/VoltageLevelTest.cpp
  test/iidm/VscConverterStationTest.cpp
Labels: PR: ready-to-be-merged

#85 Extension versioning
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/EntsoeAreaXmlSerializer.hpp
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnodeXmlSerializer.hpp
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/XnodeXmlSerializer.hpp
  extensions/entsoe/src/EntsoeAreaXmlSerializer.cpp
  extensions/entsoe/src/MergedXnodeXmlSerializer.cpp
  extensions/entsoe/src/XnodeXmlSerializer.cpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ActivePowerControlXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/CoordinatedReactiveControlXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockXmlSerializer.hpp
  extensions/iidm/src/ActivePowerControlXmlSerializer.cpp
  extensions/iidm/src/CoordinatedReactiveControlXmlSerializer.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  include/powsybl/iidm/ExtensionProvider.hpp
  include/powsybl/iidm/ExtensionProviders.hpp
  include/powsybl/iidm/converter/xml/AbstractExtensionXmlSerializer.hpp
  include/powsybl/iidm/converter/xml/AbstractVersionableExtensionXmlSerializer.hpp
  include/powsybl/iidm/converter/xml/ExtensionXmlSerializer.hpp
  include/powsybl/iidm/converter/xml/NetworkXmlReaderContext.hpp
  include/powsybl/iidm/converter/xml/VersionsCompatibity.hpp
  include/powsybl/stdcxx/map.hpp
  include/powsybl/test/converter/RoundTrip.hpp
  include/powsybl/xml/XmlStreamReader.hpp
  src/CMakeLists.txt
  src/iidm/ExtensionProvider.cpp
  src/iidm/ExtensionProviders.cpp
  src/iidm/converter/xml/AbstractExtensionXmlSerializer.cpp
  src/iidm/converter/xml/AbstractVersionableExtensionXmlSerializer.cpp
  src/iidm/converter/xml/ExtensionXmlSerializer.cpp
  src/iidm/converter/xml/NetworkXml.cpp
  src/iidm/converter/xml/NetworkXmlReaderContext.cpp
  src/iidm/converter/xml/VersionsCompatibility.cpp
  src/test/converter/RoundTrip.cpp
  src/xml/XmlStreamReader.cpp
  test/iidm/CMakeLists.txt
  test/iidm/converter/xml/CMakeLists.txt
  test/iidm/converter/xml/IdentifiableExtensionXmlSerializerTest.cpp
  test/iidm/converter/xml/extensions/ExtensionMock.cpp
  test/iidm/converter/xml/extensions/LoadMockExt.cpp
  test/iidm/converter/xml/extensions/LoadMockExt.hpp
  test/iidm/converter/xml/extensions/LoadMockExtXmlSerializer.cpp
  test/iidm/converter/xml/extensions/LoadMockExtXmlSerializer.hpp
  test/iidm/converter/xml/extensions/LoadQuxExt.cpp
  test/iidm/converter/xml/extensions/LoadQuxExt.hpp
  test/iidm/converter/xml/extensions/LoadQuxXmlSerializer.cpp
  test/iidm/converter/xml/extensions/LoadQuxXmlSerializer.hpp
  test/iidm/converter/xml/extensions/TerminalMockExt.cpp
  test/iidm/converter/xml/extensions/TerminalMockExt.hpp
  test/iidm/converter/xml/extensions/TerminalMockXmlSerializer.cpp
  test/iidm/converter/xml/extensions/TerminalMockXmlSerializer.hpp
  test/iidm/converter/xml/xiidm.cpp
  test/resources/V1_0/eurostag-tutorial-example1-with-terminalMock-ext.xml
  test/resources/V1_1/eurostag-tutorial-example1-terminalMock.xml
  test/resources/V1_1/eurostag-tutorial-example1-with-bad-loadMockExt.xml
  test/resources/V1_1/eurostag-tutorial-example1-with-bad-loadQuxExt.xml
  test/resources/V1_1/eurostag-tutorial-example1-with-terminalMock-ext.xml
Labels: PR: waiting-for-review

#84 Voltage and angle by bus in node/breaker topology
  include/powsybl/iidm/converter/Constants.hpp
  include/powsybl/iidm/converter/xml/IidmXmlUtil.hpp
  include/powsybl/iidm/util/Networks.hpp
  src/CMakeLists.txt
  src/iidm/converter/xml/BusbarSectionXml.cpp
  src/iidm/converter/xml/VoltageLevelXml.cpp
  src/iidm/converter/xml/VoltageLevelXml.hpp
  src/iidm/util/Networks.cpp
  test/resources/V1_1/fictitiousSwitchRef.xml
Labels: PR: ready-to-be-merged
