Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-12, with the labels that each got.

#206 [IIDM v1.3] Dangling line generation attribute
  include/powsybl/iidm/DanglingLine.hpp
  include/powsybl/iidm/DanglingLineAdder.hpp
  include/powsybl/iidm/DanglingLineGeneration.hpp
  include/powsybl/iidm/DanglingLineGenerationAdder.hpp
  include/powsybl/iidm/ReactiveLimitsHolder.hpp
  include/powsybl/iidm/converter/Constants.hpp
  include/powsybl/test/converter/RoundTrip.hpp
  include/powsybl/test/converter/RoundTrip.hxx
  src/CMakeLists.txt
  src/iidm/DanglingLine.cpp
  src/iidm/DanglingLineAdder.cpp
  src/iidm/DanglingLineGeneration.cpp
  src/iidm/DanglingLineGenerationAdder.cpp
  src/iidm/ReactiveLimitsHolder.cpp
  src/iidm/converter/xml/DanglingLineXml.cpp
  src/iidm/converter/xml/DanglingLineXml.hpp
  src/test/converter/RoundTrip.cpp
  test/iidm/DanglingLineTest.cpp
  test/iidm/converter/xml/LinesRoundTripTest.cpp
  test/resources/V1_0/danglingLineWithGeneration.xml
  test/resources/V1_1/danglingLineWithGeneration.xml
  test/resources/V1_2/danglingLineWithGeneration.xml
  test/resources/V1_3/danglingLineWithGeneration.xml
Labels: PR: waiting-for-correction

#208 [IIDM v1.3] Redesign IIDM shunt compensator allowing non linear shunts (#155)
  include/powsybl/iidm/ShuntCompensator.hpp
  include/powsybl/iidm/ShuntCompensator.hxx
  include/powsybl/iidm/ShuntCompensatorAdder.hpp
  include/powsybl/iidm/ShuntCompensatorLinearModel.hpp
  include/powsybl/iidm/ShuntCompensatorLinearModelAdder.hpp
  include/powsybl/iidm/ShuntCompensatorModel.hpp
  include/powsybl/iidm/ShuntCompensatorModelAdder.hpp
  include/powsybl/iidm/ShuntCompensatorModelType.hpp
  include/powsybl/iidm/ShuntCompensatorNonLinearModel.hpp
  include/powsybl/iidm/ShuntCompensatorNonLinearModelAdder.hpp
  include/powsybl/iidm/ValidationUtils.hpp
  include/powsybl/iidm/converter/Constants.hpp
  include/powsybl/stdcxx/make_unique.hpp
  include/powsybl/stdcxx/reference_wrapper.hpp
  src/CMakeLists.txt
  src/iidm/ShuntCompensator.cpp
  src/iidm/ShuntCompensatorAdder.cpp
  src/iidm/ShuntCompensatorLinearModel.cpp
  src/iidm/ShuntCompensatorLinearModelAdder.cpp
  src/iidm/ShuntCompensatorModelType.cpp
  src/iidm/ShuntCompensatorNonLinearModel.cpp
  src/iidm/ShuntCompensatorNonLinearModelAdder.cpp
  src/iidm/ValidationUtils.cpp
  src/iidm/converter/xml/AbstractIdentifiableXml.hpp
  src/iidm/converter/xml/AbstractIdentifiableXml.hxx
  src/iidm/converter/xml/ShuntCompensatorXml.cpp
  src/iidm/converter/xml/ShuntCompensatorXml.hpp
  test/iidm/BusTest.cpp
  test/iidm/ShuntCompensatorTest.cpp
  test/iidm/converter/xml/LccRoundTripRef.cpp
  test/resources/V1_0/nonLinearShuntRoundTripRef.xml
  test/resources/V1_1/nonLinearShuntRoundTripRef.xml
  test/resources/V1_2/LccRoundTripRef.xml
  test/resources/V1_2/nonLinearShuntRoundTripRef.xml
  test/resources/V1_2/shuntRoundTripRef.xml
  test/resources/V1_2/terminalRef.xml
  test/resources/V1_3/LccRoundTripRef.xml
  test/resources/V1_3/nonLinearShuntRoundTripRef.xml
  test/resources/V1_3/shuntRoundTripRef.xml
  test/resources/V1_3/terminalRef.xml
Labels: PR: corrected, PR: waiting-for-info-reviewer

#231 Fix danglingline adder
  include/powsybl/iidm/DanglingLine.hpp
  include/powsybl/iidm/DanglingLineGeneration.hpp
  include/powsybl/iidm/DanglingLineGenerationAdder.hpp
  src/iidm/DanglingLine.cpp
  src/iidm/DanglingLineAdder.cpp
  src/iidm/DanglingLineGeneration.cpp
  src/iidm/DanglingLineGenerationAdder.cpp
Labels: PR: waiting-for-review

#219 [IIDM v1.3] Fix TieLineAdder (#192)
  include/powsybl/iidm/HalfLine.hpp
  include/powsybl/iidm/HalfLineAdder.hpp
  include/powsybl/iidm/TieLine.hpp
  include/powsybl/iidm/TieLineAdder.hpp
  src/CMakeLists.txt
  src/iidm/HalfLine.cpp
  src/iidm/HalfLineAdder.cpp
  src/iidm/TieLine.cpp
  src/iidm/TieLineAdder.cpp
  src/iidm/converter/xml/TieLineXml.cpp
  src/iidm/converter/xml/TieLineXml.hpp
  test/iidm/ComponentsTest.cpp
  test/iidm/NetworkTest.cpp
  test/iidm/TieLineTest.cpp
Labels: PR: ready-to-be-merged, PR: waiting-for-coverage-test

#232 Refactoring ThreeWindingsTransformerAdder
  include/powsybl/iidm/ThreeWindingsTransformer.hpp
  include/powsybl/iidm/ThreeWindingsTransformerAdder.hpp
  include/powsybl/iidm/ThreeWindingsTransformerLeg.hpp
  include/powsybl/iidm/ThreeWindingsTransformerLegAdder.hpp
  src/CMakeLists.txt
  src/iidm/ThreeWindingsTransformer.cpp
  src/iidm/ThreeWindingsTransformerAdder.cpp
  src/iidm/ThreeWindingsTransformerLeg.cpp
  src/iidm/ThreeWindingsTransformerLegAdder.cpp
  src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
Labels: PR: waiting-for-review

#236 Add check to ensure that HalfLine is not attached twice
  src/iidm/HalfLine.cpp
Labels: PR: waiting-for-review

#199 [IIDM v1.3] Aliases on identifiables (#163)
  include/powsybl/iidm/Identifiable.hpp
  include/powsybl/iidm/Network.hpp
  include/powsybl/iidm/NetworkIndex.hpp
  include/powsybl/iidm/NetworkIndex.hxx
  include/powsybl/iidm/converter/Constants.hpp
  include/powsybl/stdcxx/map.hpp
  include/powsybl/xml/XmlStreamReader.hpp
  src/CMakeLists.txt
  src/iidm/Identifiable.cpp
  src/iidm/Network.cpp
  src/iidm/NetworkIndex.cpp
  src/iidm/converter/xml/AbstractIdentifiableXml.hxx
  src/iidm/converter/xml/AliasesXml.cpp
  src/iidm/converter/xml/AliasesXml.hpp
  src/iidm/converter/xml/NetworkXml.cpp
  src/iidm/converter/xml/ShuntCompensatorXml.cpp
  src/xml/XmlStreamReader.cpp
  test/iidm/AliasesTest.cpp
  test/iidm/CMakeLists.txt
  test/iidm/converter/xml/CMakeLists.txt
  test/iidm/converter/xml/TieLineWithAliasesXmlTest.cpp
  test/resources/V1_3/shuntRoundTripRef.xml
  test/resources/V1_3/tielineWithAliases.xml
Labels: PR: waiting-for-review

#244 Fix compilation on CentOS 7
  include/powsybl/iidm/ExtensionAdder.hpp
  include/powsybl/iidm/ShuntCompensatorLinearModelAdder.hpp
  include/powsybl/iidm/util/TerminalFinder.hpp
  include/powsybl/stdcxx/flattened.hpp
Labels: PR: waiting-for-review

#238 Update readme
  README.md
Labels: PR: ready-to-be-merged

#247 Fix Lcc/Vsc and shunts round trip tests
  test/iidm/converter/xml/CMakeLists.txt
  test/iidm/converter/xml/HvdcRoundTripTest.cpp
  test/iidm/converter/xml/ShuntCompensatorRoundTripTest.cpp
Labels: PR: ready-to-be-merged
