Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-10, with the labels that each got.

#198 [IIDM v1.3] Fix hxx guardians and hxx code cleanup
  include/powsybl/iidm/CurrentLimitsAdder.hxx
  include/powsybl/iidm/Identifiable.hxx
  include/powsybl/stdcxx/format.hxx
  src/iidm/converter/xml/AbstractConnectableXml.hxx
  src/iidm/converter/xml/AbstractIdentifiableXml.hxx
  src/iidm/converter/xml/AbstractSwitchXml.hxx
  src/iidm/converter/xml/AbstractTransformerXml.hxx
Labels: PR: ready-to-be-merged, bug

#196 [IIDM v1.3] Fictitious halfline (#187)
  include/powsybl/iidm/IdentifiableAdder.hpp
  include/powsybl/iidm/TieLine.hpp
  include/powsybl/iidm/TieLineAdder.hpp
  include/powsybl/iidm/converter/Constants.hpp
  src/iidm/TieLine.cpp
  src/iidm/TieLineAdder.cpp
  src/iidm/converter/xml/TieLineXml.cpp
  test/iidm/TieLineTest.cpp
  test/iidm/converter/xml/LinesRoundTripTest.cpp
  test/resources/V1_0/tielineFictitious.xml
  test/resources/V1_1/tielineFictitious.xml
  test/resources/V1_2/tielineFictitious.xml
  test/resources/V1_3/tielineFictitious.xml
Labels: PR: ready-to-be-merged

#197 [IIDM v1.3] Use network accessor from connectable when it is possible (#161)
  src/iidm/AbstractMultiVariantConnectableExtension.cpp
  src/iidm/ThreeWindingsTransformer.cpp
  src/iidm/converter/xml/AbstractTransformerXml.hxx
  src/iidm/converter/xml/GeneratorXml.cpp
  src/iidm/converter/xml/StaticVarCompensatorXml.cpp
Labels: PR: ready-to-be-merged

#202 G++ clang 10
  .clang-tidy
  include/powsybl/math/UndirectedGraph.hxx
  src/iidm/Connectable.cpp
  src/iidm/MergedBus.cpp
Labels: PR: waiting-for-review, bug

#193 [IIDM v1.3] Make LoadDetail a multivariant extension and moved into public API (#190)
  extensions/iidm/CMakeLists.txt
  extensions/iidm/src/Iidm.cpp
  extensions/iidm/src/LoadDetail.cpp
  include/powsybl/iidm/AbstractMultiVariantConnectableExtension.hpp
  include/powsybl/iidm/AbstractMultiVariantIdentifiableExtension.hpp
  include/powsybl/iidm/ExtensionProviders.hpp
  include/powsybl/iidm/extensions/LoadDetail.hpp
  include/powsybl/iidm/extensions/LoadDetailAdder.hpp
  src/CMakeLists.txt
  src/iidm/AbstractMultiVariantConnectableExtension.cpp
  src/iidm/AbstractMultiVariantIdentifiableExtension.cpp
  src/iidm/ExtensionProviders.cpp
  src/iidm/extensions/LoadDetail.cpp
  src/iidm/extensions/LoadDetailAdder.cpp
  src/iidm/extensions/LoadDetailXmlSerializer.cpp
  src/iidm/extensions/LoadDetailXmlSerializer.hpp
  src/logging/LoggerFactory.cpp
  test/iidm/CMakeLists.txt
  test/iidm/converter/xml/IdentifiableExtensionXmlSerializerTest.cpp
  test/iidm/extensions/LoadDetailTest.cpp
  test/resources/V1_2/loadDetailOldRef.xml
  test/resources/V1_3/loadDetailRef.xml
Labels: PR: waiting-for-review

#204 [IIDM v1.3] Extensions non copiable
  include/powsybl/iidm/Extension.hpp
Labels: PR: waiting-for-review
