Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-06, with the labels that each got.

#110 Properties moved from iidm to stdcxx namespace
  include/powsybl/iidm/Identifiable.hpp
  include/powsybl/stdcxx/Properties.hpp
  include/powsybl/stdcxx/exception.hpp
  src/CMakeLists.txt
  src/iidm/converter/xml/AbstractIdentifiableXml.hxx
  src/stdcxx/Properties.cpp
  src/stdcxx/exception.cpp
  test/iidm/CMakeLists.txt
  test/iidm/NetworkTest.cpp
  test/stdcxx/CMakeLists.txt
  test/stdcxx/PropertiesTest.cpp
Labels: PR: waiting-for-review

#108 Add XnodeAdder and use it from xml serializer
  extensions/entsoe/CMakeLists.txt
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/XnodeAdder.hpp
  extensions/entsoe/src/XnodeAdder.cpp
  extensions/entsoe/src/XnodeXmlSerializer.cpp
  extensions/entsoe/test/XnodeTest.cpp
Labels: PR: ready-to-be-merged

#107 Add ActivePowerControlAdder and use it from xml serializer
  extensions/iidm/CMakeLists.txt
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ActivePowerControlAdder.hpp
  extensions/iidm/src/ActivePowerControlAdder.cpp
  extensions/iidm/src/ActivePowerControlXmlSerializer.cpp
  extensions/iidm/test/ActivePowerControlTest.cpp
Labels: PR: ready-to-be-merged

#113 Moved ValidationUtils.hpp to public API
  extensions/entsoe/src/MergedXnode.cpp
  extensions/entsoe/src/Xnode.cpp
  include/powsybl/iidm/HvdcConverterStationAdder.hxx
  include/powsybl/iidm/ValidationUtils.hpp
  src/iidm/Battery.cpp
  src/iidm/BatteryAdder.cpp
  src/iidm/BusBreakerVoltageLevel.cpp
  src/iidm/BusTerminal.cpp
  src/iidm/BusTerminalViews.cpp
  src/iidm/BusbarSectionAdder.cpp
  src/iidm/ConfiguredBus.cpp
  src/iidm/CurrentLimits.cpp
  src/iidm/DanglingLine.cpp
  src/iidm/DanglingLineAdder.cpp
  src/iidm/Generator.cpp
  src/iidm/GeneratorAdder.cpp
  src/iidm/HvdcConverterStation.cpp
  src/iidm/HvdcLine.cpp
  src/iidm/HvdcLineAdder.cpp
  src/iidm/Identifiable.cpp
  src/iidm/InternalConnectionAdder.cpp
  src/iidm/LccConverterStation.cpp
  src/iidm/LccConverterStationAdder.cpp
  src/iidm/Line.cpp
  src/iidm/LineAdder.cpp
  src/iidm/LineCharacteristics.cpp
  src/iidm/Load.cpp
  src/iidm/LoadAdder.cpp
  src/iidm/MinMaxReactiveLimitsAdder.cpp
  src/iidm/Network.cpp
  src/iidm/NetworkIndex.cpp
  src/iidm/NodeBreakerVoltageLevel.cpp
  src/iidm/NodeTerminal.cpp
  src/iidm/PhaseTapChanger.cpp
  src/iidm/PhaseTapChangerAdder.cpp
  src/iidm/RatioTapChanger.cpp
  src/iidm/RatioTapChangerAdder.cpp
  src/iidm/ReactiveCapabilityCurveAdder.cpp
  src/iidm/ShuntCompensator.cpp
  src/iidm/ShuntCompensatorAdder.cpp
  src/iidm/StaticVarCompensator.cpp
  src/iidm/StaticVarCompensatorAdder.cpp
  src/iidm/SubstationAdder.cpp
  src/iidm/SwitchAdder.cpp
  src/iidm/TerminalBuilder.cpp
  src/iidm/ThreeWindingsTransformer.cpp
  src/iidm/ThreeWindingsTransformerAdder.cpp
  src/iidm/TieLineAdder.cpp
  src/iidm/TwoWindingsTransformer.cpp
  src/iidm/TwoWindingsTransformerAdder.cpp
  src/iidm/ValidationUtils.cpp
  src/iidm/VoltageLevel.cpp
  src/iidm/VoltageLevelAdder.cpp
  src/iidm/VscConverterStation.cpp
  src/iidm/VscConverterStationAdder.cpp
Labels: PR: waiting-for-info-author, PR: waiting-for-info-reviewer

#114 Remove useless deprecated header
  include/powsybl/test/AssertionUtils.hpp
Labels: PR: ready-to-be-merged, bug

#119 Fix RoundTrip::run method
  src/test/converter/RoundTrip.cpp
Labels: PR: waiting-for-review, bug

#132 Add the extension in read method and not by read caller
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/EntsoeAreaXmlSerializer.hpp
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnodeXmlSerializer.hpp
  extensions/entsoe/include/powsybl/iidm/extensions/entsoe/XnodeXmlSerializer.hpp
  extensions/entsoe/src/EntsoeAreaXmlSerializer.cpp
  extensions/entsoe/src/MergedXnodeXmlSerializer.cpp
  extensions/entsoe/src/XnodeXmlSerializer.cpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ActivePowerControlXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/CoordinatedReactiveControlXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockXmlSerializer.hpp
  extensions/iidm/src/ActivePowerControlXmlSerializer.cpp
  extensions/iidm/src/CoordinatedReactiveControlXmlSerializer.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  include/powsybl/iidm/converter/xml/ExtensionXmlSerializer.hpp
  src/iidm/converter/xml/NetworkXml.cpp
  test/iidm/converter/xml/extensions/LoadBarXmlSerializer.cpp
  test/iidm/converter/xml/extensions/LoadBarXmlSerializer.hpp
  test/iidm/converter/xml/extensions/LoadFooXmlSerializer.cpp
  test/iidm/converter/xml/extensions/LoadFooXmlSerializer.hpp
  test/iidm/converter/xml/extensions/LoadMockExtXmlSerializer.cpp
  test/iidm/converter/xml/extensions/LoadMockExtXmlSerializer.hpp
  test/iidm/converter/xml/extensions/LoadQuxXmlSerializer.cpp
  test/iidm/converter/xml/extensions/LoadQuxXmlSerializer.hpp
  test/iidm/converter/xml/extensions/TerminalMockXmlSerializer.cpp
  test/iidm/converter/xml/extensions/TerminalMockXmlSerializer.hpp
Labels: PR: waiting-for-review

#133 Update version to v1.1.1
  CMakeLists.txt
Labels: Breaking change, PR: next-release

#115 [IIDM v1.2] Apparent power attribute on TwoWindingsTransformer and ThreeWindingsTransformer.Leg
  include/powsybl/iidm/ThreeWindingsTransformer.hpp
  include/powsybl/iidm/ThreeWindingsTransformerAdder.hpp
  include/powsybl/iidm/TwoWindingsTransformer.hpp
  include/powsybl/iidm/TwoWindingsTransformerAdder.hpp
  include/powsybl/iidm/converter/Constants.hpp
  src/iidm/ThreeWindingsTransformer.cpp
  src/iidm/ThreeWindingsTransformerAdder.cpp
  src/iidm/TwoWindingsTransformer.cpp
  src/iidm/TwoWindingsTransformerAdder.cpp
  src/iidm/converter/xml/AbstractTransformerXml.hpp
  src/iidm/converter/xml/AbstractTransformerXml.hxx
  src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
  src/iidm/converter/xml/TwoWindingsTransformerXml.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
  test/iidm/TwoWindingsTransformerTest.cpp
  test/resources/V1_2/completeThreeWindingsTransformerRoundTripRef.xml
  test/resources/V1_2/fictitiousSwitchRef.xml
Labels: PR: ready-to-be-merged
