Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2020-03, with the labels that each got.

#12 Generate doxygen
  CMakeLists.txt
  README.md
  cmake/Doxygen.cmake
  doxygen/Doxyfile.in
  doxygen/cppreference-doxygen-web.tag.xml
  doxygen/powsybl.png
  doxygen/powsybl.svg
Labels: PR: ready-to-be-merged, documentation

#7 Add dynamic extension discovery
  CMakeLists.txt
  extensions/entsoe/CMakeLists.txt
  extensions/entsoe/src/Entsoe.cpp
  extensions/entsoe/src/EntsoeAreaXmlSerializer.cpp
  extensions/entsoe/test/EntsoeAreaTest.cpp
  extensions/entsoe/test/MergedXnodeTest.cpp
  extensions/entsoe/test/XnodeTest.cpp
  extensions/entsoe/test/entsoe.cpp
  extensions/iidm/CMakeLists.txt
  extensions/iidm/src/Iidm.cpp
  extensions/iidm/test/ActivePowerControlTest.cpp
  extensions/iidm/test/CoordinatedReactiveControlTest.cpp
  extensions/iidm/test/iidm.cpp
  include/powsybl/iidm/ExtensionProviders.hpp
  include/powsybl/iidm/ExtensionProviders.hxx
  include/powsybl/test/ExtensionFixture.hpp
  include/powsybl/test/ResourceFixture.hpp
  src/CMakeLists.txt
  src/test/CMakeLists.txt
  src/test/ExtensionFixture.cpp
  src/test/ResourceFixture.cpp
  tools/benchmark/Benchmark.cpp
Labels: PR: ready-to-be-merged

#40 Fix NodeBreakerVoltageLevel::CalculatedBusTopology::getConnectableBus
  src/iidm/NodeBreakerVoltageLevelTopology.cpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
Labels: PR: ready-to-be-merged

#39 Fix checkRatioTapChangerRegulation
  src/iidm/RatioTapChanger.cpp
  src/iidm/RatioTapChangerAdder.cpp
  src/iidm/ValidationUtils.cpp
  src/iidm/ValidationUtils.hpp
  test/iidm/RatioTapChangerTest.cpp
Labels: PR: ready-to-be-merged

#45 Implement phaseAngleClock extension for 2 and 3 windings transformers
  extensions/iidm/CMakeLists.txt
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClock.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClock.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockXmlSerializer.hpp
  extensions/iidm/resources/threeWindingsTransformerPhaseAngleClock.xml
  extensions/iidm/resources/twoWindingsTransformerPhaseAngleClock.xml
  extensions/iidm/src/Iidm.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClock.cpp
  extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClock.cpp
  extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
  extensions/iidm/test/ThreeWindingsTransformerPhaseAngleClockTest.cpp
  extensions/iidm/test/TwoWindingsTransformerPhaseAngleClockTest.cpp
  include/powsybl/network/ThreeWindingsTransformerNetworkFactory.hpp
  include/powsybl/xml/XmlStreamWriter.hpp
  src/CMakeLists.txt
  src/iidm/converter/xml/CurrentLimitsXml.cpp
  src/network/ThreeWindingsTransformerNetworkFactory.cpp
  src/xml/XmlStreamWriter.cpp
Labels: PR: ready-to-be-merged

#55 Fix the TODO in VoltageLevelXml for Bus/Branch topology
  src/iidm/converter/xml/VoltageLevelXml.cpp
Labels: PR: ready-to-be-merged

#48 New three windings transformer API
  include/powsybl/iidm/PhaseTapChanger.hpp
  include/powsybl/iidm/PhaseTapChangerAdder.hpp
  include/powsybl/iidm/PhaseTapChangerHolder.hpp
  include/powsybl/iidm/RatioTapChangerHolder.hpp
  include/powsybl/iidm/TapChanger.hpp
  include/powsybl/iidm/TapChangerHolder.hpp
  include/powsybl/iidm/ThreeWindingsTransformer.hpp
  include/powsybl/iidm/ThreeWindingsTransformer.hxx
  include/powsybl/iidm/ThreeWindingsTransformerAdder.hpp
  include/powsybl/iidm/ThreeWindingsTransformerAdder.hxx
  include/powsybl/iidm/TwoWindingsTransformer.hpp
  src/CMakeLists.txt
  src/iidm/PhaseTapChanger.cpp
  src/iidm/PhaseTapChangerAdder.cpp
  src/iidm/RatioTapChangerAdder.cpp
  src/iidm/ThreeWindingsTransformer.cpp
  src/iidm/ThreeWindingsTransformerAdder.cpp
  src/iidm/ThreeWindingsTransformerLeg2.cpp
  src/iidm/ThreeWindingsTransformerLeg2.hpp
  src/iidm/ThreeWindingsTransformerLeg3.cpp
  src/iidm/ThreeWindingsTransformerLeg3.hpp
  src/iidm/TwoWindingsTransformer.cpp
  src/iidm/ValidationUtils.cpp
  src/iidm/ValidationUtils.hpp
  src/iidm/converter/xml/AbstractConnectableXml.hpp
  src/iidm/converter/xml/AbstractConnectableXml.hxx
  src/iidm/converter/xml/AbstractTransformerXml.hpp
  src/iidm/converter/xml/AbstractTransformerXml.hxx
  src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
  src/network/ThreeWindingsTransformerNetworkFactory.cpp
  test/iidm/BusTest.cpp
  test/iidm/SubstationTest.cpp
  test/iidm/ThreeWindingsTransformerTest.cpp
  test/resources/threeWindingsTransformerRoundTripRef.xml
Labels: PR: ready-to-be-merged

#58 Fix compilation on centos
  include/powsybl/iidm/ExtensionProviders.hpp
Labels: PR: ready-to-be-merged

#56 Add name to buses based on the name of the VL
  include/powsybl/iidm/Bus.hpp
  src/iidm/Bus.cpp
  src/iidm/BusBreakerVoltageLevelTopology.cpp
  src/iidm/BusBreakerVoltageLevelTopology.hpp
  src/iidm/CalculatedBus.cpp
  src/iidm/CalculatedBus.hpp
  src/iidm/MergedBus.cpp
  src/iidm/MergedBus.hpp
  src/iidm/NodeBreakerVoltageLevelBusNamingStrategy.cpp
  src/iidm/NodeBreakerVoltageLevelBusNamingStrategy.hpp
  src/iidm/NodeBreakerVoltageLevelTopology.cpp
  test/iidm/NetworkTest.cpp
  test/iidm/NodeBreakerVoltageLevelTest.cpp
Labels: PR: ready-to-be-merged

#57 User boost::localtime which is portable
  include/powsybl/stdcxx/time.hpp
  src/CMakeLists.txt
  src/logging/LogMessage.cpp
  src/stdcxx/time.cpp
  test/logging/ContainerLoggerTest.cpp
Labels: PR: ready-to-be-merged

#68 Import/export network properties
  src/iidm/converter/xml/NetworkXml.cpp
  test/iidm/converter/xml/NetworkXmlTest.cpp
  test/resources/eurostag-tutorial1-properties.xml
Labels: PR: waiting-for-review

#66 Add a backward link to get HvdcLine to HvdcConverterStation
  include/powsybl/iidm/HvdcConverterStation.hpp
  include/powsybl/iidm/HvdcLine.hpp
  src/iidm/HvdcConverterStation.cpp
  src/iidm/HvdcLine.cpp
  test/iidm/HvdcLineTest.cpp
Labels: PR: ready-to-be-merged
