Repository powsybl/powsybl-iidm4cpp, pull requests merged in 2022-01, with the labels that each got.

#412 Fix usage of stdcxx::optional with C++-17 compliant compilers
  src/iidm/BusBreakerVoltageLevel.cpp
  src/iidm/MultipleVariantContext.cpp
Labels: PR: ready-to-be-merged, bug

#415 Fix compilation under CentOS 7 and Clang
  include/powsybl/iidm/BusCache.hpp
  include/powsybl/stdcxx/flattened.hpp
Labels: bug

#411 [IIDM v1.6.0] Move Boundary classes formulas as util (#364)
  include/powsybl/iidm/util/AbstractHalfLineBoundary.hpp
  include/powsybl/iidm/util/DanglingLineBoundary.hpp
  src/CMakeLists.txt
  src/iidm/DanglingLine.cpp
  src/iidm/HalfLineBoundary.cpp
  src/iidm/HalfLineBoundary.hpp
  src/iidm/util/AbstractHalfLineBoundary.cpp
  src/iidm/util/DanglingLineBoundary.cpp
Labels: PR: ready-to-be-merged

#407 [IIDM v1.6.0] Add InjectionObservability extension (#363)
  extensions/iidm/CMakeLists.txt
  extensions/iidm/include/powsybl/iidm/extensions/iidm/Constants.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/InjectionObservability.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/InjectionObservabilityAdder.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/InjectionObservabilityXmlSerializer.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/Observability.hpp
  extensions/iidm/include/powsybl/iidm/extensions/iidm/ObservabilityQuality.hpp
  extensions/iidm/resources/injectionObservabilityRoundTripRef.xml
  extensions/iidm/resources/injectionObservabilityRoundTripRefInvalid.xml
  extensions/iidm/src/Iidm.cpp
  extensions/iidm/src/InjectionObservability.cpp
  extensions/iidm/src/InjectionObservabilityAdder.cpp
  extensions/iidm/src/InjectionObservabilityXmlSerializer.cpp
  extensions/iidm/src/Observability.cpp
  extensions/iidm/src/ObservabilityQuality.cpp
  extensions/iidm/test/InjectionObservabilityTest.cpp
  include/powsybl/stdcxx/reference.hpp
Labels: PR: ready-to-be-merged
